<a href="https://colab.research.google.com/github/alvarocandela93/ML_googlecollab/blob/main/ML_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Set up Environment & Load Data

In [15]:
# Import data manipulation and math libraries
import pandas as pd
import numpy as np

# Import visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Import scikit-learn tools for splitting and preprocessing
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

#Mount Google Drive
from google.colab import drive
from google.colab import files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**Load Data**

In [24]:
# @title
# 1. Load the data
file_string = "/content/drive/MyDrive/brazilian_malware.csv"
df = pd.read_csv(file_string)

# Display the first few rows to ensure it loaded correctly
display(df.head())

,BaseOfCode,BaseOfData,Characteristics,DllCharacteristics,Entropy,FileAlignment,FirstSeenDate,Identify,ImageBase,ImportedDlls,...,PointerToSymbolTable,SHA1,Size,SizeOfCode,SizeOfHeaders,SizeOfImage,SizeOfInitializedData,SizeOfOptionalHeader,SizeOfUninitializedData,TimeDateStamp
0,4096,69632,783,0,5.981249,512,1970-01-01,powerbasic/win 8.00,4194304,comdlg32.dll gdi32.dll kernel32.dll ole32.dll ...,...,0,b0068836a40e6a43c6b546fcb709237e5aa223d1,76288,64855,1024,86016,2560,224,1500,12345
1,4096,1851392,783,0,6.081747,512,1970-01-01,NaN,4194304,comctl32.dll comdlg32.dll gdi32.dll kernel32.d...,...,0,5741708cd785f13b44267883e3f2fd2fa51fc23f,2558464,1843888,1024,2600960,500348,224,21476,0
2,4096,40960,783,0,5.586422,512,1970-01-01,NaN,4194304,comdlg32.dll kernel32.dll msvcrt.dll msvcrt.dl...,...,0,507fe5d8244f33d29d427468efca4ce406f23666,178688,33792,1024,33759232,177664,224,33557504,0
3,1359872,2138112,783,0,7.969464,512,1970-01-01,"upx 2.93 - 3.00 [lzma] -> markus oberhumer, la...",4194304,kernel32.dll advapi32.dll comdlg32.dll gdi32.d...,...,0,e51a7811464be1acadf6e72ba3a66aba0da438cd,806816,778240,4096,2166784,28672,224,1355776,0
4,4096,40960,783,32768,7.999900,512,1970-01-01,NaN,4194304,advapi32.dll comctl32.dll gdi32.dll kernel32.d...,...,0,0e046d9903c313ffeeb0d6392335437fe881b1f5,50689096,35840,1024,303104,38912,224,110080,0

**Data Exploration**

In [29]:
#Describe data
df.describe()

,BaseOfCode,BaseOfData,Characteristics,DllCharacteristics,Entropy,FileAlignment,ImageBase,Label,Machine,Magic,...,PE_TYPE,PointerToSymbolTable,Size,SizeOfCode,SizeOfHeaders,SizeOfImage,SizeOfInitializedData,SizeOfOptionalHeader,SizeOfUninitializedData,TimeDateStamp
count,5.018100e+04,5.018100e+04,50181.000000,50181.000000,50181.000000,50181.000000,5.018100e+04,50181.000000,50181.000000,50181.0,...,50181.0,5.018100e+04,5.018100e+04,5.018100e+04,50181.000000,5.018100e+04,5.018100e+04,50181.0,5.018100e+04,5.018100e+04
mean,1.724954e+05,8.834009e+05,18939.747016,10238.381080,6.694522,823.511050,1.636863e+08,0.579203,332.078874,267.0,...,267.0,5.513845e+05,6.895724e+06,6.789796e+05,1595.302286,2.476806e+06,1.556195e+06,224.0,1.728905e+05,1.223333e+09
std,3.721744e+06,7.145701e+06,16567.684820,15085.745309,1.145355,1012.754781,4.065986e+08,0.493692,3.074768,0.0,...,0.0,3.389692e+07,5.724471e+07,1.572283e+06,1263.993734,1.775206e+07,4.401886e+07,0.0,3.730825e+06,2.872506e+08
min,0.000000e+00,0.000000e+00,2.000000,0.000000,0.011174,32.000000,6.553600e+04,0.000000,332.000000,267.0,...,267.0,0.000000e+00,2.560000e+03,0.000000e+00,512.000000,2.944000e+03,0.000000e+00,224.0,0.000000e+00,0.000000e+00
25%,4.096000e+03,6.144000e+04,291.000000,0.000000,6.210294,512.000000,4.194304e+06,0.000000,332.000000,267.0,...,267.0,0.000000e+00,1.408000e+05,5.324800e+04,1024.000000,1.433600e+05,1.331200e+04,224.0,0.000000e+00,1.191272e+09
50%,4.096000e+03,3.358720e+05,8450.000000,1.000000,6.615470,512.000000,4.194304e+06,1.000000,332.000000,267.0,...,267.0,0.000000e+00,5.723040e+05,2.688000e+05,1024.000000,5.242880e+05,7.987200e+04,224.0,0.000000e+00,1.367470e+09
75%,4.096000e+03,7.823360e+05,33167.000000,32768.000000,7.850877,512.000000,1.093140e+08,1.000000,332.000000,267.0,...,267.0,0.000000e+00,1.981952e+06,6.906880e+05,1024.000000,1.466368e+06,2.959360e+05,224.0,0.000000e+00,1.421637e+09
max,2.457108e+08,9.415107e+08,44430.000000,60708.000000,8.000000,8192.000000,3.212837e+09,1.000000,452.000000,267.0,...,267.0,2.425393e+09,3.986104e+09,9.786982e+07,50176.000000,1.473761e+09,4.294804e+09,224.0,2.457068e+08,4.107316e+09

In [30]:
#Review data and empty values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50181 entries, 0 to 50180
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   BaseOfCode               50181 non-null  int64
 1   BaseOfData               50181 non-null  int64
 2   Characteristics          50181 non-null  int64
 3   DllCharacteristics       50181 non-null  int64
 4   Entropy                  50181 non-null  float64
 5   FileAlignment            50181 non-null  int64
 6   FirstSeenDate            50181 non-null  object
 7   Identify                 35958 non-null  object
 8   ImageBase                50181 non-null  int64
 9   ImportedDlls             50181 non-null  object
 10  ImportedSymbols          50181 non-null  object
 11  Label                    50181 non-null  int64
 12  Machine                  50181 non-null  int64
 13  Magic                    50181 non-null  int64
 14  NumberOfRvaAndSizes      50181 non-null  int64
 15  NumberOfSections         50181 non-null  int64
 16  NumberOfSymbols          50181 non-null  int64
 17  PE_TYPE                  50181 non-null  int64
 18  PointerToSymbolTable     50181 non-null  int64
 19  SHA1                     50181 non-null  object
 20  Size                     50181 non-null  int64
 21  SizeOfCode               50181 non-null  int64
 22  SizeOfHeaders            50181 non-null  int64
 23  SizeOfImage              50181 non-null  int64
 24  SizeOfInitializedData    50181 non-null  int64
 25  SizeOfOptionalHeader     50181 non-null  int64
 26  SizeOfUninitializedData  50181 non-null  int64
 27  TimeDateStamp            50181 non-null  int64
dtypes: float64(1), int64(22), object(5)
memory usage: 10.7+ MB